name: PR Review with Reviewdog

on:
  pull_request:
    paths:
      - '**.js'  # Modify this according to your project type (e.g., .js for JavaScript files)
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    
    steps:
      # Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (if you're using Node.js for ESLint or any other tool)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can change the version as needed

      # Install dependencies (e.g., ESLint or any linter you use)
      - name: Install dependencies
        run: |
          npm install

      # Run the linter and pass results to Reviewdog
      - name: Run ESLint and Reviewdog
        run: |
          npx eslint . --format=unix | reviewdog -f=unix -reporter=github-pr-review
